lena/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('users.urls'))
]

users/urls.py
from django.conf.urls import url
from . import views


app_name = 'users'
urlpatterns = [
    url(r'^$', views.UserListView.as_view(), name='list'),
    url(r'^create/$', views.UserCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.UserUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.UserDeleteView.as_view(), name='delete'),
]

users/models.py
from django.db import models
from django.core.validators import RegexValidator


class User(models.Model):
    last_name = models.CharField('Фамилия', max_length=512)
    first_name = models.CharField('Имя', max_length=512)
    phone = models.CharField('Телефон', max_length=64, validators=[RegexValidator(
        regex=r'\+7\-\([0-9]{3}\)\-[0-9]{3}\-[0-9]{4}'
    )])
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)

users/views.py
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import User


class UserListView(ListView):
    model = User


class UserCreateView(CreateView):
    model = User
    fields = ['last_name', 'first_name', 'phone']
    success_url = reverse_lazy('users:list')
    template_name_suffix = '_create'


class UserUpdateView(UpdateView):
    model = User
    fields = ['last_name', 'first_name', 'phone']
    success_url = reverse_lazy('users:list')
    template_name_suffix = '_update'

    def get_object(self, queryset=None):
        ret = super(UpdateView, self).get_object(queryset)
        print(ret)
        return ret


class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('users:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <script type="text/javascript" src='{% static 'jquery/dist/jquery.js' %}'></script>
        <script type="text/javascript" src='{% static 'js/scripts.js' %}'></script>
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap-theme.css' %}" rel="stylesheet">
        <link href="{% static 'components-font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="main-container container">
            <div class="page-header">
                <h3>{% block page_header %}{% endblock %}</h3>
            </div>
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

templates/users/user_form.html
{% extends '../base.html' %}
{% load widget_tweaks %}
{% block body %}
    <form class="form-horizontal" method="post" action="{% block form_action %}{% endblock %}" novalidate>
        {% csrf_token %}
        {%  for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}
        {%  for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error{% endif %}{% if field.field.required %} required{% endif %}">
                <label class="control-label col-sm-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field|attr:'class:form-control' }}
                    <div class="text-danger">{{ field.errors.as_text }}</div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-2"></div>
            <div class="col-sm-6">
                <input type="submit" class="btn btn-success" value="{% block submit_name %}{% endblock %}">
                <a href="{% url 'users:list' %}" class="btn btn-default">Отмена</a>
            </div>
        </div>
    </form>
{% endblock %}

templates/users/user_list.html
{% extends '../base.html' %}
{% block title %}Список пользователей{% endblock %}
{% block page_header %}Список пользователей{% endblock %}
{% block body %}
    <div class="panel-body">
        <a href="{% url 'users:create' %}" class="btn btn-primary">Создать</a>
    </div>
    <div class="panel-body">
        {% if user_list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td class="thin-as-possible">ID</td>
                        <td style="width:33%">Фамилия</td>
                        <td style="width:33%">Имя</td>
                        <td style="width:33%">Телефон</td>
                        <td class="thin-as-possible">Создано</td>
                        <td class="thin-as-possible">Изменено</td>
                        <td class="thin-as-possible"></td>
                        <td class="thin-as-possible"></td>
                    </tr>
                </thead>
                <tbody>
                    {% for user in user_list %}
                        <tr>
                            <td>{{ user.pk }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.phone }}</td>
                            <td class="text-nowrap">{{ user.created_at|date:'d.m.Y H:i:s' }}</td>
                            <td class="text-nowrap">{% if user.changed_at != user.created_at %}{{ user.changed_at|date:'d.m.Y H:i:s' }}{% endif %}</td>
                            <td><a href="{% url 'users:update' pk=user.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                            <td><a href="{% url 'users:delete' pk=user.pk %}" class="js-confirm" data-confirm="Вы уверены, что хотите удалить пользователя?"><span class="glyphicon glyphicon-remove"></span></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">Пользователи не найдены</div>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/user_create.html
{% extends './user_form.html' %}
{% block title %}Создать пользователя{% endblock %}
{% block page_header %}Создать пользователя{% endblock %}
{% block submit_name %}Создать{% endblock %}
{% block form_action %}{% url 'users:create' %}{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <form class="form-horizontal" method="post" action="{% block form_action %}{% endblock %}" novalidate>
        {% csrf_token %}
        {%  for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}
        {%  for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error{% endif %}{% if field.field.required %} required{% endif %}">
                <label class="control-label col-sm-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field|attr:'class:form-control' }}
                    <div class="text-danger">{{ field.errors.as_text }}</div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-2"></div>
            <div class="col-sm-6">
                <input type="submit" class="btn btn-success" value="{% block submit_name %}{% endblock %}">
                <a href="{% url 'users:list' %}" class="btn btn-default">Отмена</a>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_list.html
{% extends 'base.html' %}
{% block title %}Список пользователей{% endblock %}
{% block page_header %}Список пользователей{% endblock %}
{% block body %}
    <div class="panel-body">
        <a href="{% url 'users:create' %}" class="btn btn-primary">Создать</a>
    </div>
    <div class="panel-body">
        {% if user_list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td class="thin-as-possible">ID</td>
                        <td style="width:33%">Фамилия</td>
                        <td style="width:33%">Имя</td>
                        <td style="width:33%">Телефон</td>
                        <td class="thin-as-possible">Создано</td>
                        <td class="thin-as-possible">Изменено</td>
                        <td class="thin-as-possible"></td>
                        <td class="thin-as-possible"></td>
                    </tr>
                </thead>
                <tbody>
                    {% for user in user_list %}
                        <tr>
                            <td>{{ user.pk }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.phone }}</td>
                            <td class="text-nowrap">{{ user.created_at|date:'d.m.Y H:i:s' }}</td>
                            <td class="text-nowrap">{% if user.changed_at != user.created_at %}{{ user.changed_at|date:'d.m.Y H:i:s' }}{% endif %}</td>
                            <td><a href="{% url 'users:update' pk=user.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                            <td><a href="{% url 'users:delete' pk=user.pk %}" data-confirm-action="Вы уверены, что хотите удалить пользователя?"><span class="glyphicon glyphicon-remove"></span></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">Пользователи не найдены</div>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/user_update.html
{% extends './user_form.html' %}
{% block title %}Изменить пользователя{% endblock %}
{% block page_header %}Изменить пользователя{% endblock %}
{% block submit_name %}Изменить{% endblock %}
{% block form_action %}{% url 'users:update' pk=form.instance.pk %}{% endblock %}